[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
# runner = "espflash --monitor" # Select this runner for espflash v1.x.x
runner = "espflash flash --monitor"                                      # Select this runner for espflash v2.x.x
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]
# build-std-features = [
#     "panic_immediate_abort",
# ] # If additional size reduction is necessary

[env]
MCU = "esp32c3"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.1.1"
# Avoid hard error on root dir paths longer than 10 characters. To be able to actually build a `subst` on windows to a 
# shorter path should be set up and long path support for windows should be enabled through the registry
ESP_IDF_PATH_ISSUES = "warn"
